
# Meta-information about my site and blog.
title:          Andrew Wang-Hoyer
author:         Andrew Wang-Hoyer
description:    Personal playground for Andrew Wang-Hoyer
url:            http://andrew.wang-hoyer.com

exclude:
  - blog_archive
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - README.md
